apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tn10rcf8e-go
  janus-idp.io/tekton: tn10rcf8e-go
  backstage.io/kubernetes-id: tn10rcf8e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tn10rcf8e-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
